import type { Metadata } from "next";
import { public_sans } from "./components/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Clients",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${public_sans.className}`}>{children}</body>
    </html>
  );
}
